name: Minecraft Server Auto Start

on:
  push:
    branches:
      - main  
    schedule:
    - cron: "0 */5 * * *"  
  workflow_dispatch:  

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:

      - name: change directory
        run:
          cd ../../  

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Kiểm tra thư mục hiện tại
        run: pwd && ls -la

      # Cài đặt Java 21
      - name: Cài đặt Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Kiểm tra Java version
      - name: Kiểm tra Java Version
        run: java -version

      - name: Chạy Minecraft Server
        run: 
          java -Xmx16G -Xms4G -jar server.jar nogui
      
      - name: Commit & Push dữ liệu thế giới Minecraft
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add world/
          git commit -m "Auto backup Minecraft world"
          git push
