name: Minecraft Server Auto Start

on:
  push:
    branches:
      - main  
  schedule:
    - cron: "0 */3 * * *"  
  workflow_dispatch:  

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:

      - name: change directory
        run:
          cd ../../  

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Kiểm tra thư mục hiện tại
        run: pwd && ls -la

      - name: Chạy Minecraft Server
        run: 
          java -Xmx16G -Xms4G -jar server.jar nogui
