name: Minecraft Server Auto Start

on:
  push:
    branches:
      - main  # Chạy khi có cập nhật trên nhánh main
  schedule:
    - cron: "0 */3 * * *"  # Tự động chạy lại mỗi 3 giờ
  workflow_dispatch:  # Cho phép chạy thủ công

jobs:
  start-server:
    runs-on: ubuntu-latest
    steps:

      - name: Chạy Minecraft Server
        run: 
          java -Xmx16G -Xms4G -jar server.jar nogui
